name: ChaseTagLobby
version: 1.0.0
main: fr.rammex.chasetag.lobby.ChaseTagLobby
api-version: '1.21'
softdepend: [PlaceholderAPI]
permissions:
  chasetag.admin.menu:
    description: Ouvre le menu administrateur du tournoi
    default: op
commands:
  chasetag:
    description: Commandes ChaseTag
    usage: /chasetag <create|join|spectate|list>
  duel:
    description: Commandes Duel / Pratique
    usage: /duel <request|accept|decline|cancel>