redis:
  host: 141.11.114.30
  port: 25567
  password: "OHkoiujorjfoirokjdfkhou!32"

pterodactyl:
  url: https://panel.ownedcup.fr
  api-key: ptla_n5q22hVJGfkT33uGAEYLwzWQ09Qc1ih2AF4kf6I8Egq
  egg-id: 22
  external-host: 141.11.114.30
  maps:
    - name: "Temple"
      egg-id: 24
      mode: "practice"
      download-url: "http://play.ownedcup.fr:25599/temple.tar.gz"
    - name: "Sand"
      egg-id: 25
      mode: "practice"
      download-url: "http://play.ownedcup.fr:25599/sand.tar.gz"
    - name: "Mossy"
      egg-id: 26
      mode: "practice"
      download-url: "http://play.ownedcup.fr:25599/mossy.tar.gz"

mongodb:
  uri: "mongodb://TYTYTYTYYYT23!:TYsefpodpospi888888:@141.11.114.30:25574/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.8.2"
  database: "chasetag"

tournament:
  phases:
    - name: "Phase 1"
      type: "poule"
      pouleCount: 8
      playersPerPoule: 4
    - name: "Phase 2"
      type: "poule"
      pouleCount: 8
      playersPerPoule: 4
    - name: "Phase 3"
      type: "poule"
      pouleCount: 8
      playersPerPoule: 4
    - name: "Phase 4"
      type: "poule"
      pouleCount: 8
      playersPerPoule: 4
    - name: "8ème de finale"
      type: "bracket"
      bracketSize: 16
    - name: "Demi-finale"
      type: "bracket"
      bracketSize: 4
    - name: "Final"
      type: "bracket"
      bracketSize: 2

discord:
  token: "YOUR_DISCORD_TOKEN"
  guild-id: "YOUR_GUILD_ID"
  admin-role-id: "YOUR_ADMIN_ROLE_ID"
  whitelist-enabled: true
  game-logs-channel-id: ""
  staff-validation-channel-id: ""
