redis:
  host: localhost
  port: 6379
  password: ""

pterodactyl:
  url: https://panel.ton-domaine.fr
  api-key: ptla_XXXXXXXXXXXX
  external-host: 141.11.114.30
  egg-id: 5
  maps:
    - name: "Classic"
      egg-id: 5
      mode: "both"
    - name: "Map rapide"
      egg-id: 6
      mode: "practice"
    - name: "Map fun"
      egg-id: 7
      mode: "tournament"

mongodb:
  uri: "mongodb://localhost:27017"
  database: "chasetag"

tournament:
  phases:
    - name: "Phase 1"
      type: "poule"
      pouleCount: 8
      playersPerPoule: 4
    - name: "Phase 2"
      type: "poule"
      pouleCount: 8
      playersPerPoule: 4
    - name: "Phase 3"
      type: "poule"
      pouleCount: 8
      playersPerPoule: 4
    - name: "Phase 4"
      type: "poule"
      pouleCount: 8
      playersPerPoule: 4
    - name: "8ème de finale"
      type: "bracket"
      bracketSize: 16
    - name: "Demi-finale"
      type: "bracket"
      bracketSize: 4
    - name: "Final"
      type: "bracket"
      bracketSize: 2