name: ChaseTagLobby
version: 1.0.0
main: fr.rammex.chasetag.lobby.ChaseTagLobby
api-version: '1.21'
softdepend: [PlaceholderAPI]
permissions:
  chasetag.admin.menu:
    description: Ouvre le menu administrateur du tournoi
    default: op
commands:
  chasetag:
    description: Commandes ChaseTag
    usage: /chasetag <create|join|spectate|list>
  duel:
    description: Commandes Duel / Pratique
    usage: /duel <request|accept|decline|cancel>
  mute:
    description: Mute un joueur (nécessite validation Discord)
  ban:
    description: Ban un joueur (nécessite validation Discord)
  unmute:
    description: Unmute un joueur
  unban:
    description: Unban un joueur
  staff:
    description: Active le mode staff (Spectateur + outils)
  freeze:
    description: Gèle un joueur
  podium:
    description: Commandes de configuration du podium