name: ChaseTag
version: '1.0-SNAPSHOT'
main: fr.rammex.chaseTag.game.ChaseTag
api-version: '1.21'
commands:
  testgame:
    description: Lancer une partie de test
    permission: chasetag.admin
  leave:
    description: Abandonner la partie en cours
  gametestdev:
    description: Lancer une partie de test dev (avec cochon)
    permission: chasetag.admin
  arena:
    description: Commandes de gestion d'arène
    permission: chasetag.admin
  setplayer:
    description: Se mettre en mode Joueur
    permission: chasetag.admin
  setspec:
    description: Se mettre en mode Spectateur
    permission: chasetag.admin
  setstaff:
    description: Se mettre en mode Staff
    permission: chasetag.admin
