dependencies {
    implementation project(':common')

    compileOnly 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
    compileOnly 'redis.clients:jedis:5.1.0'

    implementation 'com.google.code.gson:gson:2.10.1'

    annotationProcessor 'com.velocitypowered:velocity-api:3.3.0-SNAPSHOT'
}

jar {
    from configurations.runtimeClasspath.collect {
        it.isDirectory() ? it : zipTree(it)
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}